<!DOCTYPE html>
<?php 
    if ($subsiteRoute) {
        $homeUrl = urldecode($this->url('root-subsite', array('subsite' => $subsiteRoute)));
    } else {
        $homeUrl = $this->url('home');
    }
?>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />    
    <meta charset="utf-8">
    <title>Toolbox</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link rel="shortcut icon" href="<?php echo $this->toolboxIncludeUrl;?>module/Toolbox/view/layout/img/favicon.ico" />
    <link href="<?php echo $this->toolboxIncludeUrl;?>module/Toolbox/view/layout/css/toolbox.css" rel="stylesheet"/>
    <link href="<?php echo $this->toolboxIncludeUrl;?>module/Toolbox/view/layout/css/vendor/foundation/foundation.css" rel="stylesheet"/>
    <link href="<?php echo $this->toolboxIncludeUrl;?>module/Toolbox/view/layout/css/vendor/datepicker.css" rel="stylesheet"/>
    <link href="<?php echo $this->toolboxIncludeUrl;?>module/Toolbox/view/layout/css/vendor/jquery.fancybox.css" rel="stylesheet"/>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!-- Le fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="assets/ico/apple-touch-icon-57-precomposed.png">

    <!-- project should only have one and only one of each jquery files -->
    <link href="<?=$toolboxIncludeUrl?>module/MediaManager/view/media-manager/js/jquery-ui-1.11.1.custom/jquery-ui.css" rel="stylesheet"/>

    <script src="<?php echo $this->toolboxIncludeUrl;?>widget/Vendor/js/modernizr.js"></script>
    <script src="<?php echo $this->toolboxIncludeUrl;?>module/Toolbox/view/layout/js/jquery.min.js"></script>
    <script src="<?php echo $this->toolboxIncludeUrl;?>module/Toolbox/view/layout/js/jquery-ui-1.11.1.min.js"></script>
    <script src="<?php echo $this->toolboxIncludeUrl;?>module/Toolbox/view/layout/js/foundation/foundation.js"></script>
    <script src="<?php echo $this->toolboxIncludeUrl;?>module/Toolbox/view/layout/js/foundation/foundation.offcanvas.js"></script>
    <script src="<?php echo $this->toolboxIncludeUrl;?>module/Toolbox/view/layout/js/foundation/foundation.topbar.js"></script>
    <script src="<?php echo $this->toolboxIncludeUrl;?>module/Toolbox/view/layout/js/foundation/foundation.reveal.js"></script>
    <script src="<?php echo $this->toolboxIncludeUrl;?>module/Toolbox/view/layout/js/foundation/foundation.tooltip.js"></script>
    <script src="<?php echo $this->toolboxIncludeUrl;?>module/Toolbox/view/layout/js/ckeditor/ckeditor_toolbox.js"></script>
    <script src="<?php echo $this->toolboxIncludeUrl;?>module/MediaManager/view/media-manager/js/phoenix/attachmentdialog.js"></script>
    <script src="<?php echo $this->toolboxIncludeUrl;?>module/ListModule/view/layout/js/Dropdown_DLM.js"></script>
        <script>
            var _site_root = '<?=$homeUrl?>';
            var toolboxIncludeUrl = '<?=$this->toolboxIncludeUrl?>';
        </script>
    <?=$this->headScript();?>
  </head>
<!--[if IE ]>
    <body data-offset="40" id="toolboxBody" class="ie">
<![endif]-->
<!--[if !IE]>-->
    <body id="toolboxBody" data-offset="40">
<!--<![endif]-->

<!--     Header ================================================== -->
    <header class="header">
        <div class="container">
            <div>
                <nav class="toolbox nav-bar" data-topbar role="navigation">
                    <ul class="toolbox title-area">
                        <li class="toolbox name">
                            <a href="<?php echo $this->url($toolboxRootRoute, array('subsite' => $subsiteRoute));?>" title="Toolbox CMS">
                                <img src="<?php echo $this->toolboxIncludeUrl;?>module/Toolbox/view/layout/img/dashboard_logo.png" alt="Toolbox CMS" />
                                <h1>Phoenix Toolbox</h1>
                            </a>
                        </li>
                    </ul>

                    <section class="toolbox nav-bar-section">

                        <!-- Right Nav Section -->
                        <ul class="toolbox right">
                            <li class= "toolbox">
                                <a href="tools.html">Help</a>
                            </li>
                            <li class="toolbox has-dropdown">
                                <a data-toggle="toolbox" data-hover="dropdown" class="welcome" href="#">Welcome, <?= $this->currentUser['givenName'] ?> <b class="caret"></b></a>
                                <ul class="dropdown">
                                    <li>
                                        <a href="<?php echo $this->url($toolboxRootRoute, array('subsite' => $subsiteRoute)); ?>tools/users/changeProfile/<?php echo $this->currentUser['userId'] ?>">
                                            <i class="fa fa-user"></i> Profile
                                        </a>
                                    </li>
                                    <li>
                                        <a href="<?php echo urldecode($this->url($toolboxRootRoute, array('subsite' => $subsiteRoute))); ?>?logout=1">
                                            <i class="fa fa-sign-out"></i> Logout
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>

                        <!-- Left Nav Section -->
                        <ul class="toolbox left">
                            <li class="toolbox">
                                <a href="<?php echo $this->url($toolboxRootRoute, array('subsite' => $subsiteRoute));?>">Home</a>
                            </li>
                            <li class="toolbox has-dropdown">
                                <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" href="#">Content Tools <b class="caret"></b></a>
                                <ul class="toolbox dropdown">
                                    <?= $this->getDropdownNavigation(count($this->toolList), 'up', 10) ?>
                                    <li class="has-dropdown">
                                        <a href="#" data-dropdown="dlmDrop" data-toggle="dropdown" data-hover="dropdown" data-options="align: right" class="data-toggle">DLM</a>
                                        <ul id="dlmDrop" class="toolbox dropdown f-dropdown drop-right">

                                            <?= $this->getDropdownNavigation(count($this->dlmToolList), 'up') ?>
                                            <?php foreach($this->dlmToolList as $toolName => $toolPath):?>
                                                <li><a href="<?php echo $toolboxHomeUrl . $toolPath;?>"><?= trim(str_replace('DLM', '', $this->camelCaseToWords($toolName))); ?></a></li>
                                            <?php endforeach;?>
                                            <?= $this->getDropdownNavigation(count($this->dlmToolList), 'down') ?>

                                        </ul>
                                    </li>
                                    <li><a href="<?php echo $homeUrl;?>">Site Content</a></li>
                                    <!---<li><a href="media.html">Media Manager</a></li>-->

                                    <?php foreach($this->toolList as $toolName => $toolPath):?>
                                        <li><a href="<?php echo $toolboxHomeUrl . $toolPath;?>"><?php echo $toolName;?></a></li>
                                    <?php endforeach;?>
                                    <?= $this->getDropdownNavigation(count($this->toolList), 'down', 10) ?>

                                </ul>
                            </li>

                        <?php if ($this->isAdmin):?>

                            <li class="toolbox has-dropdown">
                                <a data-toggle="dropdown" data-hover="dropdown" class="" href="#">Admin Tools <b class="caret"></b></a>
                                <ul class="toolbox dropdown">

                                <?= $this->getDropdownNavigation(count($this->adminToolList), 'up') ?>
                                <?php foreach($this->adminToolList as $toolName => $toolPath):?>
                                    <li><a href="<?php echo $toolboxHomeUrl . $toolPath;?>"><?php echo $toolName;?></a></li>
                                <?php endforeach;?>
                                <?= $this->getDropdownNavigation(count($this->adminToolList), 'down') ?>

                                </ul>
                            </li>

                        <?php endif;?>

                        <?php if ($this->isDeveloper):?>

                            <li class="toolbox has-dropdown">
                                <a data-toggle="dropdown" data-hover="dropdown" class="" href="#">Dev Tools <b class="caret"></b></a>
                                <ul class="toolbox dropdown">

                                <?= $this->getDropdownNavigation(count($this->devToolList), 'up') ?>
                                <?php foreach($this->devToolList as $toolName => $toolPath):?>
                                    <li><a href="<?php echo $toolboxHomeUrl . $toolPath;?>"><?php echo $toolName;?></a></li>
                                <?php endforeach;?>
                                <?= $this->getDropdownNavigation(count($this->devToolList), 'down') ?>

                                </ul>
                            </li> 

                        <?php endif;?>

                        </ul>
                    </section>
                </nav>
            </div>
        </div>
    </header>

    <!-- Navbar ================================================== -->
    
    <!-- Container =============================================== -->
    <div class="container contents">
        <div class="row">
            <div class="small-12 columns">
                <div id="notifications">

                <?php if ($this->getCasInfo()->getPendingItemCount()>0) : ?>

                    <div class="cas alert-box warning radius"><a href="<?= $this->url('contentApproval-toolbox')?>"><i class="fa fa-exclamation-circle cas fa-2x"></i><span><?= $this->getCasInfo()->getPendingItemCount() ?> Pending Change<?php if ($this->getCasInfo()->getPendingItemCount()!=1) echo 's' ?> require<?php if ($this->getCasInfo()->getPendingItemCount()==1) echo 's' ?> approval</span></a></div>

                <?php endif ?>

                <?= $this->flashMessenger()->render('default', array('alert-box info radius'))?> 
                <?= $this->flashMessenger()->render('success', array('alert-box success radius'))?> 
                <?= $this->flashMessenger()->render('info', array('alert-box warning radius'))?> 
                <?= $this->flashMessenger()->render('error', array('alert-box alert radius'))?> 

                </div>
            </div>
        </div>

        <!-- Contents ================================================ -->
        <div class="row">
            <div class="small-12 columns">
            <?php echo $this->content; ?>

            <!-- Toolbox-wide handlebars templates -->
            <?php
                echo $this->partial('errorNotification');
                echo $this->partial('successNotification');
            ?>
            </div>
        </div>

        <!-- Attachments Dialog ====================================== -->
        <?php if (!$attachmentsDisabled):?>
            <style>
                /** stopgap */
                #attachmentDialog {
                    display : none;
                }
            </style>
            <div id="attachmentDialog" class="mmDialog row">
                <?= $this->partial('mediaManager', array(
                    'toolboxIncludeUrl' => $this->toolboxIncludeUrl,
                    'isAttachments' => 'true'));
                ?>
            </div> 
        <?php endif; ?>

        <!-- Footer ================================================== -->
        <div class="row">
            <div class="small-12 columns">
                <footer class="footer">
                    <hr />
                    <p>
                        <a href="http://www.travelclick.net/" title="Visit Trav" target="_blank">
                            <img class="img_tc_footer" src="<?php echo $this->toolboxIncludeUrl;?>module/Toolbox/view/layout/img/travelclick_footer_logo.png" alt="TravelCLICK Logo">
                        </a>

                        &copy; Copyright - All Rights Reserved <?=date('Y');?> <strong>Version: <?php echo PHOENIX_VERSION . '-' . PHOENIX_VERSION_DATE;?></strong>

                        <!-- Hide for now 
                        <span class="right">
                            <a href="#">
                                <span class="fa-stack fa-sm">
                                    <i class="fa fa-square fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a> 
                            <a href="#">
                                <span class="fa-stack fa-sm">
                                    <i class="fa fa-square fa-stack-2x"></i>
                                    <i class="fa fa-google-plus fa-stack-1x fa-inverse"></i>
                                </span>
                            </a> 
                            <a href="#">
                                <span class="fa-stack fa-sm">
                                    <i class="fa fa-square fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a> 
                        </span>-->
                    </p>
                </footer>
            </div>
        </div>
    </div>
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster-->
     <script src="<?php echo $this->toolboxIncludeUrl;?>module/Toolbox/view/layout/js/fancybox/jquery.fancybox.js"></script>
   <script src="<?php echo $this->toolboxIncludeUrl;?>module/Toolbox/view/layout/js/fancybox-init.js"></script>
<script>
//Drag N Drop Scripts

    function addNewButton(element) {
        var newButton = $('<input type="button" name="btnAdd" value="Add Rate" class="add-new" id="addNew"/>');
        newButton.appendTo(element);             
    }

    $( document ).ready(function() {
        addNewButton($('.selectRates'));
        $('.selectRate').first().children('.up-button').hide();
        $('.selectRate').last().children('.down-button').hide();

        $('#addNew').on('click', function(){
            resetButtons($('.selectRate').last());
            var newRate = $('.selectRate').last().clone();
            // newRate.children('.up-button').click(moveUp(newRate.children('.up-button')));
            // newRate.children('.down-button').click(moveDown(newRate.children('.down-button')));
            // newRate.children('.delete-button').click(deleteRow(newRate.children('.delete-button')));
            newRate.insertAfter($('.selectRate').last());
            resetFirstLastButtons();
            enableButtons();            
        });

        $('.up-button').click(function(){
            var upClicked = $(this).parent('.selectRate').insertBefore($(this).parent('.selectRate').prev());
            resetButtons($(this).parent('.selectRate').next());        
            resetButtons(upClicked);
            resetFirstLastButtons();
        });

        $('.down-button').click(function(){
            var downClicked = $(this).parent('.selectRate').insertAfter($(this).parent('.selectRate').next());
            resetButtons(downClicked);
            resetButtons($(this).parent('.selectRate').prev());        
            resetFirstLastButtons();
        });

        $('.delete-button').click(function(){
           $(this).parent('.selectRate').remove();
           resetFirstLastButtons(); 
        });

        $('.dropdown-navigation-down').each(function () {
            var downBtn = $(this),
                upBtn = downBtn.siblings('.dropdown-navigation-up'),
                items = downBtn.siblings(':not(.dropdown-navigation-up, .js-generated)'),
                limit = downBtn.data('item-limit');

            // hide anything over the limit
            items.each(function (index, elem) {
                if (index + 1 > limit) {
                    $(elem).hide();
                }
            });

            upBtn.addClass('disabled').unbind('click').click(function () {
                if (!upBtn.hasClass('disabled')) {
                    downBtn.removeClass('disabled');

                    items.filter(':visible:first').prev().show();
                    items.filter(':visible:last').hide();

                    if (items.filter(':first').is(':visible')) {
                        upBtn.addClass('disabled');
                    }
                }
            });

            downBtn.unbind('click').click(function () {
                if (!downBtn.hasClass('disabled')) {
                    upBtn.removeClass('disabled');


                    items.filter(':visible:last').next().show();
                    items.filter(':visible:first').hide();

                    if (items.filter(':last').is(':visible')) {
                        downBtn.addClass('disabled');
                    }
                }
            });
        });
    });

    function enableButtons()
    {
        var lastRow = $('.selectRate').last();
        lastRow.children('.up-button').click(function(){
            var upClicked = $(this).parent('.selectRate').insertBefore($(this).parent('.selectRate').prev());
            resetButtons($(this).parent('.selectRate').next());        
            resetButtons(upClicked);
            resetFirstLastButtons();
        });

        lastRow.children('.down-button').click(function(){
            var downClicked = $(this).parent('.selectRate').insertAfter($(this).parent('.selectRate').next());
            resetButtons(downClicked);
            resetButtons($(this).parent('.selectRate').prev());        
            resetFirstLastButtons();
        });

        lastRow.children('.delete-button').click(function(){
           $(this).parent('.selectRate').remove();
           resetFirstLastButtons(); 
        });
    }

    function resetButtons(resetElement)
    {
        resetElement.children('.up-button').show();
        resetElement.children('.down-button').show();
    }

    function resetFirstLastButtons()
    {
      $('.selectRate').first().children('.up-button').hide();
      $('.selectRate').first().children('.down-button').show();
      $('.selectRate').last().children('.up-button').show();
      $('.selectRate').last().children('.down-button').hide();        
    }

    function moveUp(element)
    {
        var upClicked = element.parent('.selectRate').insertBefore(element.parent('.selectRate').prev());
        resetButtons(element.parent('.selectRate').next());        
        resetButtons(upClicked);
        resetFirstLastButtons();        
    }

    function moveDown(element)
    {
        var downClicked = element.parent('.selectRate').insertAfter(element.parent('.selectRate').next());
        resetButtons(downClicked);
        resetButtons(element.parent('.selectRate').prev());        
        resetFirstLastButtons();      
    }

    function deleteRow(element)
    {
       element.parent('.selectRate').remove();
       resetFirstLastButtons();         
    }    

    $(document).foundation();

    if ($(document).foundation === undefined) {
        throw new Error('Foundation is undefined');
    } else {
        $(document).foundation();
    }
</script>  
  <?php echo $this->inlineScript();?>
  </body>
</html>