<div id="editBox">
    <div id="editBoxHeader">
        <div id="editItemHeaderTitle"><?= $title ?></div>
         <?= $this->partial('list-module/helpers/edit-list-actions') ?>
    </div>
    <div class="editListContent">
        <form method="POST">
            <input type="hidden" name="action" value="" />
            <table class="table table-compacted" id="example">

			<thead>
                    <tr>
                        <th width="20px">No</th>
                        <th width="40px">Room Code</th>
                        <th width="20px">Room Name</th>
						<th width="40px">Room Subscription</th>
						<th width="40px">Room Description</th>
                        <th width="40px">Status</th>
                    </tr>
                </thead>
                <tbody id="sortable">
                <?php foreach($this->items as $index => $list): ?>
                    <tr class="ui-state-default" data-itemId="<?= $list->getId() ?>">
                        <td>
						<?= $list->getId() ?>
						</td>
                        <td>
                        <?= $list->getcode() ?>                            
                        </td>
                        <td><?= $list->getname() ?></td>
						 <?php
                        if($list->getSubscribe()==1)
                            $type = "Subscribe";
                        else
                            $type = "Not Subscribe";
                        ?>
                        <td><?= $type ?></td>
						<td><?= $list->getdescription() ?> : <?= $list->getbedtype() ?></td>
                        <td><?= $this->displayStatus($list->getStatus()) ?></td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </form>
        <?= $this->partial('list-module/helpers/edit-list-pagination') ?>
    </div>
</div>