<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'PhoenixSite\Module'                       => __DIR__ . '/Module.php',
  'PhoenixSite\Entity\PhoenixSiteComponents' => __DIR__ . '/src/PhoenixSite/Entity/PhoenixSiteComponents.php',
  'PhoenixSite\Helper\PhoenixSites'          => __DIR__ . '/src/PhoenixSite/Helper/PhoenixSites.php',
  'PhoenixSite\Model\Site'                   => __DIR__ . '/src/PhoenixSite/Model/Site.php',
  'PhoenixSite\Model\SiteComponent'          => __DIR__ . '/src/PhoenixSite/Model/SiteComponent.php',
  'PhoenixSite\Service\Components'           => __DIR__ . '/src/PhoenixSite/Service/Components.php',
);
