<div class="editItemOptionsList">
    <div id="edit-cancel" data-action="" class="editItemOption" onclick="window.location = '<?php echo $this->toolboxHomeUrl;?>tools/users_listUsers-en.html';showWait(); return false;">
        <img src="<?php echo $this->toolboxIncludeUrl;?>module/Users/view/layout/img/cancel.png">
        <span>Cancel</span>
    </div>
    <div id="edit-save" data-action="save" class="editItemOption" onclick="document.user.submit(); showWait(); return false;">
        <img src="<?php echo $this->toolboxIncludeUrl;?>module/Users/view/layout/img/save.png">
        <span>Save</span>
    </div>
    &nbsp;
</div>