<div id="editBox">
    <div id="editBoxHeader">
        <div id="editItemHeaderTitle"><?= $title ?></div>
        <? //= $this->partial('list-module/helpers/edit-list-actions') ?>
    </div>
    <div class="editListContent">
        <form method="POST">
            <input type="hidden" name="action" value="" />
            <table class="table table-compacted" id="example">
                <thead>
                    <tr>
                        <th width="20px"></th>
                        <th>Language</th>
                        <th>Code</th>
                        <th>English Name</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->items as $page) {?>
                    <tr>
                        <td><? //<input type="checkbox" name="items[]" value="<?= $page->getId() ? >" />?></td>
                        <td><? //<a href="<? //= $this->url('languages-toolbox', array('subsite' => $subsiteRoute, 'action'=>'editItem', 'itemId'=>$page->getId())) ? >">?><?= $page->getName() ?><?//</a>?></td>
                        <td><?=$page->getCode()?></td>
                        <td><?=$page->getEnglishName()?></td>
                        <td class="statusText"><?= $this->displayStatus($page->getEntity()->getStatus()) ?></td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </form>
    </div>
    <? //$this->partial('list-module/helpers/edit-list-pagination') ?>
</div>