<!DOCTYPE html>
<div id="modalEditHeader" class="reveal-modal tiny" data-reveal>
    <a class="close-reveal-modal">&#215;</a>
    <h3>Are you sure you want to modify the header?</h3>
    <ul class="stack-for-small round secondary button-group">
        <li><a href="#" id="editHeader"  class="button alert tiny">Yes</a></li>
        <li><a href="#" id="cancelHeader" class="button tiny">No</a></li>
    </ul>
</div>

<div id="modalEditFooter" class="reveal-modal tiny" data-reveal>
    <a class="close-reveal-modal">&#215;</a>
    <h3>Are you sure you want to modify the footer?</h3>
    <ul class="stack-for-small round secondary button-group">
        <li><a href="#" id="editFooter"  class="button alert tiny">Yes</a></li>
        <li><a href="#" id="cancelFooter" class="button tiny">No</a></li>
    </ul>
</div>