<?php echo $this->doctype(); ?>
    <head class="wasfkdjasdfasdfasd">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php echo $this->headTitle('PhoenixTNG')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php 
            echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/vendor/bootstrap/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/vendor/bootstrap/bootstrap.min.css');
        ?>

        <!-- Scripts -->
        <?php
            echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                    ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                    ->prependFile($this->basePath() . '/js/jquery.min.js')
                                    ->prependFile($this->basePath() . '/js/ckeditor/ckeditor.js');
        ?>

    </head>
    <body>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2013 - <?php echo date('Y') ?> by TravelClick, Inc. <?php echo $this->translate('All rights reserved.') ?></p>
                <hr>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>