<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'PhoenixProperties\Module'                                 => __DIR__ . '/Module.php',
  'PhoenixProperties\Controller\SocketsController'           => __DIR__ . '/src/PhoenixProperties/Controller/SocketsController.php',
  'PhoenixProperties\Controller\ToolboxController'           => __DIR__ . '/src/PhoenixProperties/Controller/ToolboxController.php',
  'PhoenixProperties\Entity\PhoenixProperty'                 => __DIR__ . '/src/PhoenixProperties/Entity/PhoenixProperty.php',
  'PhoenixProperties\Form\PropertyForm'                      => __DIR__ . '/src/PhoenixProperties/Form/PropertyForm.php',
  'PhoenixProperties\Model\Property'                         => __DIR__ . '/src/PhoenixProperties/Model/Property.php',
  'PhoenixProperties\Model\PropertyUser'                     => __DIR__ . '/src/PhoenixProperties/Model/PropertyUser.php',
  'PhoenixProperties\Service\GoogleMapContent'               => __DIR__ . '/src/PhoenixProperties/Service/GoogleMapContent.php',
  'PhoenixProperties\Service\Properties'                     => __DIR__ . '/src/PhoenixProperties/Service/Properties.php',
  'PhoenixProperties\Service\SubmoduleAbstract'              => __DIR__ . '/src/PhoenixProperties/Service/SubmoduleAbstract.php',
  'PhoenixProperties\Service\SubmoduleNonIntegratedAbstract' => __DIR__ . '/src/PhoenixProperties/Service/SubmoduleNonIntegratedAbstract.php',
  'PhoenixProperties\Service\UserLoginRedirect'              => __DIR__ . '/src/PhoenixProperties/Service/UserLoginRedirect.php',
);
