<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<div class="row">
    <div class="column large medium small text-center">
        <h1>Home</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="column callout panel large-12 medium-12 small-12">
            <p><h1>Welcome to The Hotel Name</h1></p>
            <p><h2>H2 EXAMPLE TEXT FOR SEO PURPOSES</h2></p>
        </div>
    </div>
    <div class="row">
        <div class="column callout panel large-12 medium-12 small-12">HOME PAGE WIDGET</div>
    </div>
</div>
