<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>

<div class="row">
    <div class="column large medium small text-center">
        <h1>Footer</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="column callout panel large-7 medium-7 small-7">FOOTER NAVIGATION</div>
        <div class="column callout panel large-5 medium-5 small-5">MEDIA TOOLBAR</div>
    </div>
    
    <div class="row">
        <div class="column callout panel large-6 medium-6 small-6">FOOTER CONTACT</div>
        <div class="column callout panel large-6 medium-6 small-6">
            <div class="row">
                <div class="column callout panel large-6 medium-6 small-6">AWARD SLIDE</div>
                <div class="column callout panel large-6 medium-6 small-6">NEWSLETTER SIGN-UP</div>
            </div>
        </div>
    </div>
</div>