<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>

<div class="row">
    <div class="column large medium small text-center">
        <h1>Header</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="column callout panel large-2 medium-2 small-6">LOGO</div>
        <div class="column callout panel large-4 medium-4 small-4"></div>
        <div class="column callout panel large-6 medium-10 small-6">NAVIGATION</div>
    </div>
    <div class="row">
        <div class="column callout panel large-12 medium-12 small-12">HEROIMAGE</div>
    </div>
    <div class="row">
        <div class="column callout panel large-12 medium-12 small-12">BOOKING</div>
    </div>
</div>