<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<div class="row">
    <div class="column large medium small text-center">
        <h1>Sidebar</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="column callout panel large-12 medium-12 small-12">WEATHER WIDGET</div>
    </div>
    <div class="row">
        <div class="column callout panel large-12 medium-12 small-12">BOOKING WIDGET</div>
    </div>
    <div class="row">
        <div class="column callout panel large-12 medium-12 small-12">EVENT WIDGET</div>
    </div>
</div>