<div id="fileManager" class="row">
	<div id="fileToolbar" class="column small-12 fileHeaderBar">
		<div id="openedFolderName" data-rel="<?=$baseFolder;?>" class="fileHeading">File Browser</div>
		<div id="fileManagerSearchButton"><i class="fa fa-search"></i></div>

		<!-- this hack prevents jquery-ui from focusing on the first element, our searchbox, which has a handler -->
		<span class="ui-helper-hidden-accessible"><input type="text"/></span>

		<input id="fileManagerSearchBox" type="text">
		<span class="closeFileManager"><i class="fa fa-close"></i></span>
	</div>
	<div class="off-canvas-wrap">
		<div class="inner-wrap">
			<nav class="left-off-canvas-menu">
				<div id="fileExplorer"></div>
			</nav>
			<div id="fileExplorerTab"><i class="fa fa-arrow-right"></i></div>
			<div id="fileViewer" class="row">
				<div id="fileViewerInner"></div>	
			</div>
		</div>
	</div>
</div>
