<h2>This is the Toolbox Dashboard</h2>

<?php echo $this->simpleMenu(array(
    'Properties' => '/toolbox/tools/phoenixProperties',
    'Rates' => '/toolbox/tools/phoenixRates',
    'Addons' => '/toolbox/tools/phoenixAddons',
    'Rooms' => '/toolbox/tools/phoenixRooms',
    'Attributes' => '/toolbox/tools/phoenixAttributes',
    'Users' => '/toolbox/tools/users',
	'ImageSwitch' => '/toolbox/tools/imageSwitch'
    ));