<div id="editBox">
    <div id="editBoxHeader">
        <div id="editItemHeaderTitle"><?= $title ?></div>
        <? //= $this->partial('list-module/helpers/edit-list-actions') ?>
    </div>
    <div class="editListContent">
        <form method="POST">
            <input type="hidden" name="action" value="" />
            <table class="table table-compacted" id="example">
                <thead>
                    <tr>
                        <th width="20px"></th>
                        <th>Property</th>
                        <th>Languages</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->items as $properties) {?>
                    <tr>
                        <td></td>
                        <td><a href="<?= $this->url('languages-toolbox', array('subsite' => $subsiteRoute, 'action'=>'editItem', 'controller'=> 'properties', 'itemId'=>$properties->property->getId())) ?>"><?= $properties->property->getName() ?></a></td>
                        <td>
                            <?php $properties->languages[$properties->defaultCode] = '<strong>' . $properties->languages[$properties->defaultCode] . '</strong>';
                            echo implode(',', $properties->languages);?>
                        </td>
                        <td></td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </form>
    </div>
    <? //$this->partial('list-module/helpers/edit-list-pagination') ?>
</div>