<div id="editBox">
    <div id="editItemHeader" class="editItemHeader">
        <h2 id="editItemHeaderTitle"><?= $this->taskTitle ?></h2>
        <?= $this->partial('users/helpers/edit-user-actions') ?>
    </div>
    <div class="editItemContent">
        <br/>
        <div class="editItemMessage">
            <?php if ($this->userAdded) : ?>
                echo 'The user has been added.<hr>';
            <?php endif; ?>

            <?php if ($this->hasErrors) : ?>
                <?= $this->formElementErrors($this->form); ?>
            <?php endif; ?>
        </div>

        <?php
            echo $this->form()->openTag($this->form);
            foreach ($this->form as $valForm) {
                if ($valForm instanceof \Zend\Form\Element\Hidden) {
                    echo $this->formHidden($valForm);
                } else {
                    echo '<p>' . $this->formLabel($valForm) . $this->formElement($valForm) . '</p>';
                    echo str_replace('Value is required', $valForm->getName() . ' is required', $this->formElementErrors($valForm, array('class' => 'error-inline')));
                }
            }
            echo $this->form()->closeTag();
        ?>
    </div>
    <?= $this->partial('users/helpers/edit-user-actions') ?>
</div>