<?php echo $this->headLink()->prependStylesheet($this->toolboxIncludeUrl . '/module/Users/view/layout/css/general.css'); ?>

<div id="resetBox" >
    <form  method="POST">
        <p>
            <label id="loginPassResetInfo">Please enter your username and we will send you an e-mail to reset your password.</label>
        </p>
        <p>
            <label id="loginPasswordLabel" for="loginPassword">Username:</label>
            <input id="loginPassword" type="text" value="" name="username">

        </p>

        <input type="submit" name="submit" value="Change Password" style="position: absolute; top: 153px; right: 20px; "/>

    </form>
</div>
<?php if ($this->error): ?>
    <div id="loginError"><?php echo $this->errorMessage; ?></div>
<?php endif; ?>
