<?php echo $this->headLink()->prependStylesheet($this->toolboxIncludeUrl . '/module/Users/view/layout/css/general.css'); ?>

<div id="loginBox">
    <form method="POST">
        <p><label id="loginUserLabel" for="loginUsername">Password : </label><input type="password" id="loginUsername" name="password" value="" /></p>
        <p><label id="loginPasswordLabel" for="loginPassword">Confirm Password:</label><input type="password" id="loginPassword" name="confirm_password" /></p>
      
        <input type="submit" name="submit" value="Update Password" style="position: absolute; top: 153px; right: 20px; "/>
                 <p><a id="passwordResetLink" href="<?php echo $this->url($this->actionRoute, $this->actionTokens);?>" >Go Back</a></p>
    </form>
    
    </div>
<?php if ($this->error): ?>
    <div id="loginError"><?php echo $this->errorMessage;?></div>
<?php endif;?>

