<div id="editBox">
    <div id="editBoxHeader">
        <div id="editItemHeaderTitle">Manage Blocks</div>
        <?= $this->partial('list-module/helpers/edit-list-actions') ?>
    </div>
    <div class="editListContent">
        <form method="POST">
            <input type="hidden" name="action" value="" />
            <table class="table table-compacted" id="example">
                <thead>
                    <tr>
                        <th width="20px"></th>
                        <th>ID</th>
                        <th>Name</th>
                        <th width="80px">Status</th>
                    </tr>
                </thead>
                <tbody>
                <?php 
                $replace = array(
                    "/",
                    "\\"
                );
                foreach ($items as $locationKey=>$subpages): ?>
                    <tr>
                        <td><input type="checkbox" name="items[]" value="<?= $subpages->getId() ?>" /></td>
                        <td>
                            <a href="<?= $this->url('blocks-toolbox', array('action' => 'editItem', 'itemId' => $subpages->getId())) ?>">
                                <?= $subpages->getId() ?>
                            </a>
                        </td>
                       
                        <td><a href="<?= $this->url('blocks-toolbox', array('action' => 'editItem', 'itemId' => $subpages->getId())) ?>">
                                <?= $subpages->getName() ?>
                            </a></td>
                        <td><?= $this->displayStatus($subpages->getStatus()) ?></td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </form>
        <?= $this->partial("list-module/helpers/edit-list-pagination") ?>
    </div>
</div>