<?php

function testSite($r, $logFile) {
    if (!($url = trim($r['url']))) {
        return;
    }
    try {
        $html = file_get_contents($url);
    } catch (Exception $ex) {
        file_put_contents($logFile, "$url could not load page\r\n", FILE_APPEND);
        return;
    }
    if (!$html) {
        file_put_contents($logFile, "$url could not load page\r\n", FILE_APPEND);
        return;
    }
    $tokens = array('page_home', 'page_default', 'page_dining');
    if (!preg_match('/('.implode('|', $tokens).')/', $html, $m)) {
        file_put_contents($logFile, "$url could not find any of tokens: ".implode(', ', $tokens)."\r\n", FILE_APPEND);
        return;
    }
}

function displayLog($logFile) {
    echo str_replace("\r\n", '<br/>', file_get_contents($logFile));
}

$logFile = getcwd().'/testlog.txt';
unlink($logFile);
$conn = new MySqli("10.30.25.218", "trafficdbuser", "9$9c8DdE", 'htb_phoenixtng');
$res = $conn->query("SELECT * FROM sites");
while ($r=$res->fetch_assoc()) {
    testSite($r, $logFile);
}

displayLog($logFile);