<div id="editBox">
    <div id="editBoxHeader">
        <div id="editItemHeaderTitle"><?= $title ?></div>
         <?= $this->partial('list-module/helpers/edit-list-actions') ?>
    </div>
    <div class="editListContent">
        <form method="POST">
            <input type="hidden" name="action" value="" />
            <table class="table table-compacted" id="example">

			<thead>
                    <tr>
                        <th width="20px"></th>
                        <th width="40px">Name</th>
                        <th width="20px">Email</th>
						<th width="40px">Subscribe</th>
						<th width="40px">Country</th>
                        <th width="40px">Status</th>
                    </tr>
                </thead>
                <tbody id="sortable">
                <?php foreach($this->items as $index => $mailingList): ?>
                    <tr class="ui-state-default" data-itemId="<?= $mailingList->getId() ?>">
                        <td><input type="checkbox" name="items[]" value="<?= $mailingList->getId() ?>" /></td>
                        <td>
                            <a href="<?= $this->url('mailingList-toolbox', array('subsite'=> $subsiteRoute, 'action'=>'editItem', 'itemId'=>$mailingList->getId())) ?>">
                                <?= $mailingList->getfirstName() ?>
                            </a>
                        </td>
                        <td><?= $mailingList->getEmail() ?></td>
						 <?php
                        if($mailingList->getSubscribe()==1)
                            $type = "Subscribe";
                        else
                            $type = "Not Subscribe";
                        ?>
                        <td><?= $type ?></td>
						<td><?= $mailingList->getCountryCode() ?></td>
                        <td><?= $this->displayStatus($mailingList->getStatus()) ?></td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </form>
        <?= $this->partial('list-module/helpers/edit-list-pagination') ?>
    </div>
</div>