<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>

<div class="row">
    <div class="column large medium small text-center">
        <h1>Home</h1>
    </div>
</div>
<div class="container">
    <div class="column large-12 medium-12 small-12">
        <div class="row">
            <div class="home-features column callout panel large-6 medium-6 small-12 text-center">
                Features
            </div>
            <div class="home-offers column callout panel large-6 medium-6 small-12 text-center">
                Special Offers
            </div>
        </div>
    </div>
    <div class="column large-12 medium-12 small-12 test" style="background: #f9f9f9;">
        <div class="row">
            <div class="home-whatson column callout panel large-6 medium-12 small-12 text-center">
                What's on / Events
            </div>
            <div class="home-location column callout panel large-6 medium-12 small-12 text-center">
                Location
            </div>
        </div>
    </div>
    <div class="column large-12 medium-12 small-12">
        <div class="row">
            <div  contenteditable="false"  class="editable column large-9 medium-6 small-12 text-left">
                <h1>H1 WELCOME TO HOTEL NAME</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nec ligula lacinia, bibendum massa sit amet, fermentum nunc. Suspendisse tincidunt quis lacus vitae auctor. Maecenas dapibus purus a consequat imperdiet. Praesent sit amet mollis mi. <br><br>Phasellus rhoncus viverra nunc, vel tincidunt metus vehicula eget. Donec ac metus id risus varius vulputate vitae et diam. Vivamus at leo nisl. Aliquam erat volutpat. Etiam nibh felis, interdum pellentesque ornare non, elementum ac elit. Phasellus sem neque, ultricies sed urna et, elementum mollis urna.</p>
            </div>
            <div class="column callout panel large-3 medium-6 small-12 text-center">
                Text Carousel
            </div>
        </div>
    </div>
</div>
