<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>

<div class="row">
    <div class="column large medium small text-center">
        <h1>Events</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="column callout panel large-12 medium-12 small-12">Breadcrumb</div>
    </div>
    <div class="row">
        <div contenteditable="false"  class="editable column small-12">
            <h1>H1 for SEO purposes</h1>
            <p>Ut enim ad minim veniam, quis nostrud exercita tion ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
        </div>
    </div>

    <div class="row">
        <div class="column callout panel small-12">
            Calendar widget
        </div>
    </div>
</div>
