<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>

<div class="row">
    <div class="column large medium small text-center">
        <h1>Facilities</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="column callout panel large-12 medium-12 small-12 text-left">Breadcrumb</div>
    </div>
    <div class="row">
        <div  contenteditable="false"  class="editable column large-12 medium-12 small-12 text-left">
            <h1>H1 for SEO purposes</h1>
            <p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.</p>
            <p>Fusce enim lectus, porta dictum lectus ac, semper congue tellus. Vivamus rutrum tincidunt risus, id posuere velit tristique vitae. Ut et cursus ante. Donec convallis diam egestas, aliquet lectus at, accumsan est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce dignissim commodo felis, eget congue diam lobortis eget.</p>
        </div>
    </div>
    <div class="row">
        <div class="column callout panel large-12 medium-12 small-12 text-center">
            List module (DLM) Widget
        </div>
    </div>
</div>
