<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>

<div class="row">
    <div class="column large medium small text-center">
        <h1>Footer</h1>
    </div>
</div>

<div class="container">
    <div class="column large-12 medium-12 small-12" style="background: #555555; border-bottom: 1px solid #fff;">
        <div class="row">
            <div class="column callout panel large-6 medium-6 small-12 text-left">
                Footer Navigation
            </div>
            <div class="column callout panel large-6 medium-6 small-12 text-right">
                Social Toolbar
            </div>
        </div>
    </div>
    <div class="column large-12 medium-12 small-12" style="background: #555555;">
        <div class="row">
            <div class="column callout panel large-6 medium-8 small-12 hide-for-small-only text-left">
                Logo Partner
            </div>
            <div class="column callout panel large-6 medium-4 small-12 text-right">
                Weather
            </div>
        </div>
    </div>
    <div class="column large-12 medium-12 small-12" style="background: #E2E2E2;">
        <div class="row">
            <div class="column large-6 medium-12 text-left large-12 callout panel">
                Street name, 00, 01010 Location, COUNTRY | T: +00 000 000 000 | F: +00 000 000 000 | Email: info@mail.com <span class="text-right right">&copy;&nbsp;2014</span>
            </div>            
        </div>
    </div>
</div>