<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>

<div class="row">
    <div class="column large-12 medium-12 small-12 text-center">
        <h1>Header</h1>
    </div>
</div>
<div class="container">
    <div class="contain-to-grid">
        <div class="row">
            <div id="header-template1" class="columns small-12">
                <div class="row">
                    <div class="column callout panel small-2">LOGO</div>
                    <div class="column callout panel small-1">LANG</div>
                    <div class="column callout panel small-9">NAVIGATION</div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="column callout panel large-12 medium-12 small-12">SLIDER</div>
    </div>
    <div class="row">
        <div class="column callout panel large-3 medium-3 small-12">BOOKING</div>
    </div>
</div>