<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>

<div class="row">
    <div class="column large medium small text-center">
        <h1>Rooms</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="column callout panel large-12 medium-12 small-12 text-left">Breadcrumb</div>
    </div>
    <div class="row">
        <div  contenteditable="false"  class="editable column large-12 medium-12 small-12 text-left">
            <h1>H1 Rooms SEO text</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dignissim justo eros, vel vulputate nisi tincidunt rutrum. Phasellus malesuada neque et elit fringilla aliquam. Sed dolor nulla, dictum nec blandit adipiscing, fermentum eget nisl. In eget diam mattis, egestas lorem id, elementum odio. Curabitur dolor turpis, placerat at lorem vel, blandit pulvinar orci. Nullam facilisis neque et elementum accumsan. Sed dui metus, sagittis sed lacinia vel, adipiscing vel ligula. Quisque id quam vel dolor congue vehicula. Donec id urna at lacus cursus fringilla a nec est. Fusce enim lectus, porta dictum lectus ac, semper congue tellus. Vivamus rutrum tincidunt risus, id posuere velit tristique vitae. Ut et cursus ante. Donec convallis diam egestas, aliquet lectus at, accumsan est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce dignissim commodo felis, eget congue diam lobortis eget.</p>
        </div>
    </div>
    <div class="row">
        <div class="column callout panel large-12 medium-12 small-12 text-center">
            Rooms Widget
        </div>
    </div>
</div>
