<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>

<div class="row">
    <div class="column large medium small text-center">
        <h1>Sitemap</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="column callout panel large-12 medium-12 small-12 text-left">Breadcrumb</div>
    </div>
    <div class="row">
        <div class="column callout panel large-12 medium-12 small-12 text-center">
            Sitemap widget
        </div>
    </div>
</div>
