<div id="editBox">
    <div id="editBoxHeader">
        <div id="editItemHeaderTitle"><?= $title ?></div>
         <?= $this->partial('list-module/helpers/edit-list-actions') ?>
    </div>
    <div class="editListContent">
        <form method="POST">
            <input type="hidden" name="action" value="" />
            <table class="table table-compacted" id="example">
                <thead>
                    <tr>
                        <th width="20px"></th>
                        <th width="auto">Title</th>
                        <th width="90px">GA Account</th>
                        <th width="90px">Domain</th>
                        <th width="80px">Status</th>
                    </tr>
                </thead>
                <tbody id="sortable">
                <?php foreach($this->items as $index => $googleAnalytics): ?>
                    <tr class="ui-state-default" data-itemId="<?= $googleAnalytics->getId() ?>">
                        <td><input type="checkbox" name="items[]" value="<?= $googleAnalytics->getId() ?>" /></td>
                        <td>
                            <a href="<?= $this->url('googleAnalytics-toolbox', array('subsite'=> $subsiteRoute, 'action'=>'editItem', 'itemId'=>$googleAnalytics->getId())) ?>">
                                <?= $googleAnalytics->getTitle() ?>
                            </a>
                        </td>
                        <td><?= $googleAnalytics->getGaAccount() ?></td>
                        <td><?= $googleAnalytics->getDomain() ?></td>
                        <td><?= $this->displayStatus($googleAnalytics->getStatus()) ?></td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </form>
        <?= $this->partial('list-module/helpers/edit-list-pagination') ?>
    </div>
</div>