<?php //print_r($options);   ?>
<?php if ($options['DryRun']) : ?>
    Please approve desired changes and submit the form below
    <br />
    <br />
    <form method="post">
        <div class="importResult">
            <table class="table table-compacted">
                <thead>
                    <tr>
                        <th width="80px">Hotel code</th>
                        <th width="auto">Hotel name</th>
                        <th width="60px">Duration</th>
                        <th width="80px">Language</th>
                        <th width="60px">Status</th>
                        <th width="60px">Approve<br /><a class="approve-all" href="javascript:;">Select all</a></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($removeList as $code => $hotel) : ?>
                        <tr class="error">
                            <td><a href="#"><?= $code ?></a></td>
                            <td><?= $hotel['name'] ?></td>
                            <td><?= gmdate('H:i:s', 0) ?></td>
                            <td>English</td>
                            <td>Removed</td>
                            <td><input class="approve-checkbox" type="checkbox" name="approve[]" value="<?= $code ?>" /></td>
                        </tr>
                        <tr style="display: none;">
                            <td colspan="10">
                                <?php var_dump($hotel->data_object) ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    <?php foreach ($this->results as $key => $hotel) : ?>
                        <tr class="<?= $hotel->status_class ?>">
                            <td><a href="#"><?= $hotel->code ?></a></td>
                            <td><?= $hotel->name ?></td>
                            <td><?= gmdate('H:i:s', $hotel->duration / 1000) ?></td>
                            <td><?= $this->languages[$hotel->language] ?></td>
                            <td><?= $hotel->status_text ?></td>
                            <td><?php if ($hotel->status_text != 'Skipped') : ?><input class="approve-checkbox" type="checkbox" name="approve[]" value="<?= $hotel->code ?>" /><?php endif ?></td>
                        </tr>

                    <?php endforeach; ?>
                </tbody>
            </table>
        </div><br />
        <?php foreach ($hotelParams as $param) : ?>
            <input type="hidden" name="hotel[]" value="<?= $param ?>" />
        <?php endforeach ?>
        <?php foreach ($languageParams as $param) : ?>
            <input type="hidden" name="language[]" value="<?= $param ?>" />
        <?php endforeach ?>
        <input type="hidden" value="Import" name="import" />
        <input type="submit" value="Submit" class="btn pull-right" />
    </form>
<?php else : ?>

    Approved changes have been applied.
    <br /><br />
<?php endif; ?>

<script type="text/javascript">
    $('.approve-all').click(function() {
        $('.approve-checkbox').each(function() {
            $(this).prop('checked', true);
        });
    });
    $('#hotel').hide();
</script>