<?php if ($options['DryRun']) : ?>
    Please approve desired changes and submit the form below
    <br />
    <br />
    <form method="post">
        <div class="importResult">
            <table class="table table-compacted">
                <thead>
                    <tr>
                        <th width="80px">Hotel code</th>
                        <th width="80px">Rate code</th>
                        <th width="auto">Rate name</th>
                        <th width="60px">Duration</th>
                        <th width="80px">Language</th>
                        <th width="60px">Status</th>
                        <th width="60px">Approve<br /><a class="approve-all" href="javascript:;">Select all</a></th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (($options['Criteria'] == '') && (count(explode(',', $options['Criteria'])) == 1)) : ?>
                        <?php foreach ($removeList as $code => $rate) : ?>
                            <tr class="error">
                                <td><?= $rate['hotelCode'] ?></td>
                                <td><a href="#"><?= $code ?></a></td>
                                <td><?= $rate['name'] ?></td>
                                <td><?= gmdate('H:i:s', 0) ?></td>
                                <td>English</td>
                                <td>Removed</td>
                                <td><input class="approve-checkbox" type="checkbox" name="approve[]" value="<?= $code ?>" /></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif ?>
                    <?php foreach ($this->results as $key => $rate) : ?>
                        <tr class="<?= $rate->status_class ?>">
                            <td><?= $rate->hotel_code ?></td>
                            <td><?= $rate->code ?></td>
                            <td><?= $rate->name ?></td>
                            <td><?= gmdate('H:i:s', $rate->duration / 1000) ?></td>
                            <td><?= $this->languages[$rate->language] ?></td>
                            <td><?= $rate->status_text ?></td>
                            <td><?php if ($rate->status_text != 'Skipped') : ?><input class="approve-checkbox" type="checkbox" name="approve[]" value="<?= $rate->code ?>" /><?php endif ?></td>

                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <br />
        <?php foreach ($hotelParams as $param) : ?>
            <input type="hidden" name="hotel[]" value="<?= $param ?>" />
        <?php endforeach ?>
        <?php foreach ($languageParams as $param) : ?>
            <input type="hidden" name="language[]" value="<?= $param ?>" />
        <?php endforeach ?>
        <input type="hidden" value="1" name="override" />
        <input type="hidden" value="Import" name="import" />
        <input type="submit" value="Submit" class="btn pull-right" />
    </form>

<?php else : ?>

    Approved changes have been applied.
    <br /><br />
<?php endif; ?>

<script type="text/javascript">
    $('.approve-all').click(function() {
        $('.approve-checkbox').each(function() {
            $(this).prop('checked', true);
        });
    });
    $('#rate').hide();
</script>

