
<div id="editBox">
    <div id="editBoxHeader">
        <div id="editItemHeaderTitle"><?= $title ?></div>
        <?= $this->partial('list-module/helpers/edit-list-actions') ?>
    </div>
    <div class="editListContent">
        <form method="POST">
            <input type="hidden" name="action" value="" />
            <table class="table table-compacted" id="example">
                <thead>
                    <tr>
                        <th width="20px"></th>
                        <th width="190px">Property</th>
                        <th width="auto">Name</th>
                        <th width="60px">Code</th>
                        <th width="80px">Corporate</th>
                        <th width="80px">Featured</th>
                        <th width="70px">Status</th>
                    </tr>
                </thead>
                <tbody id="sortable">
                <?php foreach ($this->items as $valAddon): ?>
                    <?php $addon = $valAddon->getEntity(); ?>
                    <tr class="ui-state-default" data-itemId="<?= $valAddon->getId() ?>">
                        <td><input type="checkbox" name="items[]" value="<?= $addon->getId() ?>" /></td>
                        <td><?= $addon->getProperty()->getName() ?></td>
                        <td>
                            <a href="<?= $this->url('phoenixAddons-toolbox', array('subsite' => $subsiteRoute, 'action'=>'editItem', 'itemId'=>$addon->getId())) ?>">
                                <?= $addon->getName() ?>
                            </a>
                        </td>
                        <td><?= $addon->getCode() ?></td>
                        <td><?= $this->displayYesNo($addon->getProperty()->getIsCorporate()) ?></td>
                        <td><?= $this->displayYesNo($addon->getFeatured()) ?></td>
                        <td><?= $this->displayStatus($addon->getStatus()) ?></td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </form>
        <? //$this->partial('list-module/helpers/edit-list-pagination') ?>
    </div>
</div>