
<div id="editBox">
    <div id="editBoxHeader">
        <div id="editItemHeaderTitle"><?= $title ?></div>
        <?= $this->partial('list-module/helpers/edit-list-actions') ?>
    </div>
    <div class="editListContent">
        <form method="POST">
            <input type="hidden" name="action" value="" />
            <table class="table table-compacted" id="example">
                <thead>
                    <tr>
                        <th width="20px"></th>
                        <th width="190px">Property</th>
                        <th width="auto">Name</th>						
                        <th width="100px">Booking Link</th>
						<th width="40px">Price</th>                 
                        <th width="70px">Status</th>
                    </tr>
                </thead>
                <tbody id="sortable">
                <?php foreach ($this->items as $room) { ?>
                    <tr class="ui-state-default" data-itemId="<?= $room->getId() ?>">
                        <td><input type="checkbox" name="items[]" value="<?= $room->getId() ?>" />
                        <td><?= $room->getProperty()->getName() ?></td>
                        <td>
                            <a href="<?= $this->url('phoenixRooms-toolbox', array('action'=>'editItem', 'subsite' => $subsiteRoute, 'itemId'=>$room->getId())) ?>">
                                <?= $room->getName() ?>
                            </a>
                        </td>						
						<td><?= $room->getBookingLink() ?></td>
						<td> $<?= $room->getPrice() ?></td>                       
                        <td><?= $this->displayStatus($room->getStatus()) ?></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </form>
        <? //$this->partial('list-module/helpers/edit-list-pagination') ?>
    </div>
</div>