<div id="editBox">
    <div id="editBoxHeader">
        <div id="editItemHeaderTitle"><?= $title ?></div>
        <?= $this->partial('list-module/helpers/edit-list-actions') ?>
    </div>
    <div class="editListContent">
        <form method="POST">
            <input type="hidden" name="action" value="" />
            <table class="table table-compacted" id="example">
                <thead>
                    <tr>
                        <th width="20px"></th>
                        <th>Page</th>
                        <th>Title</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->items as $heroImage) : ?>
                        <tr>
                            <td><input type="checkbox" name="items[]" value="<?= $heroImage->getId() ?>" /></td>
                            <td><a href="<?= $this->url('pages-toolbox', array('subsite' => $subsiteRoute, 'action'=>'editItem', 'itemId'=>$heroImage->getPageId())) ?>"><?=$this->getHeroImagePage($heroImage->getPageId())?></a></td>
                            <td><a href="<?= $this->url('heroImages-toolbox', array('subsite' => $subsiteRoute, 'action'=>'editItem', 'itemId'=>$heroImage->getId())) ?>"><?=$heroImage->getTitle()?></a></td>
                          

                            <td class="statusText"><?= $this->displayStatus($heroImage->getEntity()->getStatus()) ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </form>
    </div>
    <? //$this->partial('list-module/helpers/edit-list-pagination') ?>
</div>