
<?php $this->inlineScript()->captureStart() ?>
$("#languageSelect").change(function() {
        var changedLanguage = $(this).val();
        var currentLanguage = $('input[name="currentLanguage"]').val();
        
        // ckeditor
        for(name in CKEDITOR.instances)
        {
            CKEDITOR.instances[name].destroy()
        }
        var translateFields = JSON.parse('<?php echo json_encode($this->translateFields);?>');

        translateFields.forEach(function(element, index, array) {
                var fieldName = element[0];
                var fieldType = element[1];
                var currentFieldName = fieldName + '_' + currentLanguage;
                var changedFieldName = fieldName + '_' + changedLanguage;

                var fieldPrefix = 'input';

                if(fieldType == "textarea")
                {
                    editor = CKEDITOR.instances[fieldName];
                    var edata = editor.getData();
                    editor.setData($(fieldPrefix + '[name=' + changedFieldName + ']').val());
                }
                else
                {
                    $(fieldPrefix + '[name=' + currentFieldName + ']').val($(fieldPrefix +  '[name=' + fieldName + ']').val());
                    $(fieldPrefix + '[name=' + fieldName + ']').val($(fieldPrefix + '[name=' + changedFieldName + ']').val());
                }
            }
        );
        $('input[name="currentLanguage"]').val(changedLanguage); 
    }
);
<?php $this->inlineScript()->captureEnd() ?>
<div id="editBox">
    <div id="editItemHeader" class="editItemHeader">
        <h2 id="editItemHeaderTitle"><?= $title ?></h2>
        <div id="editItemLangSelect" class="editItemLangSelect">
            <span>LANGUAGE &nbsp;</span>
            <?php echo $this->formElement($this->languageOptions);?>
        </div>
        <?= $this->partial('list-module/helpers/edit-item-actions') ?>
    </div>
    <div class="editItemContent">
        <br/>
        <div class="editItemMessage"></div>
        <?php echo $this->form()->openTag($form); ?>
        <?php foreach ($this->form as $valForm) {

            if ($valForm instanceof \Zend\Form\Element\Hidden) {
                echo $this->formHidden($valForm);
            } else {
                echo '<p>' . $this->formLabel($valForm);
                if ($valForm instanceof \Phoenix\Form\Element\OrderedSelect) {
                    echo $this->formOrderedSelect($valForm);
                } else {
                    echo $this->formElement($valForm);
                }
                echo '</p>';
                echo str_replace('Value is required', $valForm->getName() . ' is required', $this->formElementErrors($valForm, array('class' => 'error-inline')));
            }
        } ?>
        <?php echo $this->form()->closeTag(); ?>
    </div>
    <?= $this->partial('list-module/helpers/edit-item-actions') ?>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        var url = '<?= $this->url('heroImages-attachmentToolbox', array('subsite' => $subsiteRoute, 'action'=>'attachmentInfo'))?>',
            editImageMessage = '';
            // editImageMessage = 'Edit image text';

        $('.media-attachment-item').each(function(){
            $(this).append('<br /><a href="'+url+'/'+$(this).attr('ref')+'" style="bottom: 10px; top: auto;right: 15px;">' + editImageMessage + '</a>');
        });
    });
</script>