<?php if ($this->pageCount): ?>
<div>
	<ul class="pagination">
    <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
      <li>
        <a href="<?php echo $this->url($this->route); ?>?page=<?=$this->previous?>&search=<?=$search?>">
          <i class="fa fa-caret-left"></i>
        </a>
      </li>
    <?php else: ?>
      <li><a class="disabled"><i class="fa fa-caret-left"></i></a></li>
    <?php endif; ?>

    <!-- Numbered page links -->
    <?php foreach ($this->pagesInRange as $page): ?>
      <?php if ($page != $this->current): ?>
        <li><a href="<?php echo $this->url($this->route); ?>?page=<?=$page?>&search=<?=$search?>">
          <?php echo $page; ?>
        </a></li>
      <?php else: ?>
        <li class="current"><a href="#"><?php echo $page; ?></a></li>
      <?php endif; ?>
    <?php endforeach; ?>

    <!-- Next page link -->
    <?php if (isset($this->next)): ?>
      <li>
        <a href="<?php echo $this->url($this->route); ?>?page=<?=$this->next?>&search=<?=$search?>">
          <i class="fa fa-caret-right"></i>
        </a>
      </li>
    <?php else: ?>
      <li><a href="disabled"><i class="fa fa-caret-right"></i></a></li>
    <?php endif; ?>
  </ul>
</div>
<?php endif; ?>