<?php
$title = 'Change Password';
$this->headTitle($title);
?>
<div class="editBox">
 <div class="editBoxHeader">
   <h2 class="editBoxHeaderTitle"><?php echo $this->escapeHtml ($title); ?></h2>
   <div class="optionsList">
    <ul>
      <li onclick="document.user.submit(); showWait(); return false;">
	    <img class="editListBoxButton" title="Save" src="<?php echo $this->condorBaseHREF; ?> templates/toolbox/images/confirmOff.png" onmouseover="this.src='<?php echo $this->condorBaseHREF;?> templates/toolbox/images/confirmOn.png';" onmouseout="this.src='<?php echo $this->condorBaseHREF; ?> templates/toolbox/images/confirmOff.png';" height="25" width="25" alt="" />
	  </li>
	  <li onclick="window.location = '<?php echo $this->toolboxHomeUrl; ?> tools/youfirst_listUser-en.html';showWait(); return false;">
	    <img class="editBoxButton" title="Cancel" src="<?php echo $this->condorBaseHREF?> templates/toolbox/images/cancelOff.png" onmouseover="this.src='<?php echo $this->condorBaseHREF?> templates/toolbox/images/cancelOn.png';" onmouseout="this.src='<?php echo $this->condorBaseHREF?> templates/toolbox/images/cancelOff.png';" height="25" width="25" alt="" />	  
	  </li>
	 </ul>   
   </div> 
 </div>
 <div class="editBoxContent">
  <h4>Username: <?php echo $this->username; ?></h4>
  <?php
  $form = $this->form;
  $form->setAttribute('action', $this->url('youfirst-toolbox', array('action' => 'changePassword')));
  $form->prepare();
  
  if ($this->userAdded) {
    echo 'The user has been updated.<BR>';
  }
  elseif ($this->hasErrors) {
    echo $this->formElementErrors($this->form);
  }
  
  echo $this->form()->openTag($form);
  
  foreach ($this->form as $valForm) {
    if ($valForm instanceof \Zend\Form\Element\Hidden) {
	  echo $this->formHidden($valForm);
	}
	else
	{
	  echo '<p>' . $this->formLabel($valForm) . $this->formElement($valForm) . '</p>';
	  echo str_replace('Value is required', $valForm->getName(), . ' is requried', $this->formElementErrors($valForm, array('class' => 'error-inline')));
	}
   }
  
   echo $this->form()->closeTag(); 
  
  ?>
</div>