<?php 
 $title = 'YouFirst Login';
 $this->headTitle($title);
?>
<div class="editBox">
 <div class="editBoxContent">
   <h4>YouFirst Login</h4>
   <?php echo $this->email; 
    $form = $this->form;
	$form->setAttribute('action', $this->url('youfirst-toolbox', array('action' => 'getUserInfo')));
	$form->prepare();

    if ($this->userPassword) {
      echo 'The temp password has been sent.<BR>';
    }
    elseif ($this->hasErrors) {
     echo $this->formElementErrors($this->form);
    }

    echo $this->form()->openTag($form);

    foreach ($this->form as $valForm) {
     if ($valForm instanceof \Zend\Form\Element\Hidden) {
	  echo $this->formHidden($valForm);
	 }
	 else {
	   echo '<p>' . $this->formLabel($valForm) . $this->formElement($valForm) . '</p>';
	   echo str_replace('Value is required', $valForm->getName(), . ' is required', $this->formElementErrors($valForm, array ('class' => 'error-inline')));
	  }

    }	
   
   
   ?>
 </div>
</div>
   