<script id="uploadProgressTemplate" type="x-handlebars-template">
	<li class="working row" data-canvasnumber="{{ canvasNumber }}">
		<input type="text" value="0" data-width="48" data-height="48" data-fgColor="#0788a5" data-readOnly="1" data-bgColor="#3e4043" />
		<div class="uploaded_file_text column small-offset-1 small-9"></div>
		<div class="column small-1 closeUploadProgressWrapper"><i class="fa fa-close closeUploadProgress"></i></div>
	</li>
</script>

