<div id="editBox">
    <div id="editBoxHeader">
        <div id="editItemHeaderTitle">Edit Page</div>
        <?= $this->partial('list-module/helpers/edit-list-actions') ?>
    </div>
    <div class="editListContent">
        <form method="POST">
            <input type="hidden" name="action" value="" />
            <table class="table table-compacted" id="example">
                <thead>
                    <tr>
                        <th width="20px"></th>
                        <th width="40">DataSection</th>
						<th width="auto">Name</th>
                        <th width="80px">Status</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($items as $locationKey=>$subpages): ?>
                    <tr>
                        <td><input type="checkbox" name="items[]" value="<?= $subpages->getId() ?>" /></td>
                        <td>
                            <a href="<?= $this->url('siteMaps-toolbox', array('subsite' => $subsiteRoute, 'action' => 'editItem', 'itemId' => $subpages->getItemId())) ?>">
                                <?= $subpages->getAreaKey() . " > " . $subpages->getPageKey() ?> 
                            </a>
                        </td>
                        <td><?= $this->displayStatus($subpages->getStatus()) ?></td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </form>
        <?= $this->partial('list-module/helpers/edit-list-pagination') ?>
    </div>
</div>
