<div id="editBox">
    <div id="editBoxHeader">
        <div id="editItemHeaderTitle"><?= $title ?></div>
        <?= $this->partial('list-module/helpers/edit-list-actions') ?>
    </div>
    <div class="editListContent">
        <form method="POST">
            <input type="hidden" name="action" value="" />
            <table class="table table-compacted" id="list-wrapper">
                <thead>
                    <tr>
                        <th></th>
                        <th>Type</th>
                        <th>Area</th>
                        <th>Name</th>
                        <th>LangCode</th>
                        <th>Text</th>
                        <th>status</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->items as $key => $polytext): ?>
                    <tr>
                        <td><input type="checkbox" name="items[]" value="<?= $polytext->getId() ?>" /></td>
                        <td><?= $polytext->getType() ?></td>
                        <td>
                            <a href="<?= $this->url('polytext-toolbox', array('action'=>'editItem', 'itemId'=>$polytext->getId())) ?>">
                                <?= $polytext->getArea() ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?= $this->url('polytext-toolbox', array('action'=>'editItem', 'itemId'=>$polytext->getId())) ?>">
                                <?= $polytext->getName() ?>
                            </a>
                        </td>
                        <td><?= $polytext->getLang() ?></td>
                        <td><?= $polytext->getText() ?></td>
                        <td><?= $this->displayStatus($polytext->getStatus()) ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </form>
        <?= $this->partial('list-module/helpers/edit-list-pagination') ?>
    </div>
</div>