<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'ListModule\Module'                               => __DIR__ . '/Module.php',
  'ListModule\Controller\CategoryToolboxController' => __DIR__ . '/src/ListModule/Controller/CategoryToolboxController.php',
  'ListModule\Controller\SocketsController'         => __DIR__ . '/src/ListModule/Controller/SocketsController.php',
  'ListModule\Controller\ToolboxController'         => __DIR__ . '/src/ListModule/Controller/ToolboxController.php',
  'ListModule\Entity\Categories'                    => __DIR__ . '/src/ListModule/Entity/Categories.php',
  'ListModule\Entity\Entity'                        => __DIR__ . '/src/ListModule/Entity/Entity.php',
  'ListModule\Form\CategoryForm'                    => __DIR__ . '/src/ListModule/Form/CategoryForm.php',
  'ListModule\Form\Form'                            => __DIR__ . '/src/ListModule/Form/Form.php',
  'ListModule\Form\View\Helper\FormElement'         => __DIR__ . '/src/ListModule/Form/View/Helper/FormElement.php',
  'ListModule\Helper\DisplayStatus'                 => __DIR__ . '/src/ListModule/Helper/DisplayStatus.php',
  'ListModule\Helper\DisplayYesNo'                  => __DIR__ . '/src/ListModule/Helper/DisplayYesNo.php',
  'ListModule\Helper\ItemInformation'               => __DIR__ . '/src/ListModule/Helper/ItemInformation.php',
  'ListModule\Helper\ListUpdateStatusButtons'       => __DIR__ . '/src/ListModule/Helper/ListUpdateStatusButtons.php',
  'ListModule\Helper\ListUpdateStatusScript'        => __DIR__ . '/src/ListModule/Helper/ListUpdateStatusScript.php',
  'ListModule\Model\Category'                       => __DIR__ . '/src/ListModule/Model/Category.php',
  'ListModule\Model\ListItem'                       => __DIR__ . '/src/ListModule/Model/ListItem.php',
  'ListModule\Service\Categories'                   => __DIR__ . '/src/ListModule/Service/Categories.php',
  'ListModule\Service\Lists'                        => __DIR__ . '/src/ListModule/Service/Lists.php',
  'ListModule\StdLib\FormHelper'                    => __DIR__ . '/src/ListModule/StdLib/FormHelper.php',
);
