<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<div class="row">
    <div class="column large medium small text-center">
        <h1>Awards</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="column large-12 medium-12 small-12 text-left">
            <p>Breadcrumb</p>
        </div>
    </div>
    <div class="row">
        <div contenteditable="false"  class="editable column large-12 medium-12 small-12">
            <h1>Award Page</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ac malesuada ligula, at aliquet quam. Morbi pharetra dolor id tellus hendrerit eleifend. Duis sed diam eget quam cursus faucibus sed ut dolor. Nam nec luctus turpis. In sagittis lectus hendrerit facilisis egestas. Vivamus ut tortor ante. Suspendisse vitae massa leo. Aliquam vel hendrerit erat. Vestibulum vel dui sit amet mi rutrum ornare vitae non nulla. In aliquet dui vitae turpis aliquam, non imperdiet lectus iaculis. Aenean blandit tincidunt nisi in malesuada. Aenean vitae ante varius, posuere mi et, placerat ipsum. Mauris sit amet interdum ante, vitae blandit orci. Fusce dolor eros, convallis sit amet magna non, laoreet ullamcorper ligula. Vivamus eu sapien ultrices, cursus augue et, mollis purus.</p>
        </div>
    </div>
    <div class="row">
        <div class="column callout panel large-12 medium-12 small-12">
            Awards Widget
        </div>
    </div>
</div>