<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>

<div class="row">
    <div class="column large medium small text-center">
        <h1>Contact</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="column large-12 medium-12 small-12 text-left">
            <p>Breadcrumb</p>
        </div>
    </div>
    <div class="row">
        <div contenteditable="false"  class="editable column large-12 medium-12 small-12 text-left">
            <h1>H1 for SEO purposes</h1>
        </div>
    </div>
    <div class="row">
        <div class="column large-12 medium-12 small-12 text-left">
            <p><ul>
                <li>
                    <h3>Address</h3>
                    <p>999 Phasellus Ante Felis, Solor sit Amet, <br>Lorem ipsum 00987</p>
                </li>
                <li>
                    <h3>Telephone</h3>
                    <p>787-895-632</p>
                </li>
                <li>
                    <h3>Fax</h3>
                    <p>787-222-999</p>
                </li>
                <li>
                    <h3>E-mail</h3>
                    <p>ohacseliuys@mail.com</p>
                </li>
            </ul></p>
        </div>
    </div>
    <div class="row">
        <div class="column callout panel large-12 medium-12 small-12 text-center">
            Contact Form
        </div>
    </div>
    <div class="row">
        <div class="column callout panel large-12 medium-12 small-12 text-center">
            Maps
        </div>
    </div>
</div>