<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>

<div class="row">
    <div class="column large medium small text-center">
        <h1>Footer</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="column callout panel large-6 medium-6 small-6 text-left">
            Footer Nav
        </div>
        <div class="column callout panel large-6 medium-6 small-6 text-right">
            Social Icons
        </div>
    </div>
    <div class="row">
        <div class="column large-12 medium-12 text-left">
            <p>Stree name, 00, 01010 Location, COUNTRY T: +00 000 000 000 F: +00 000 000 000 Email: info@mail.com</p>
        </div>
    </div>
    <div class="row">
        <div class="column callout panel large-12 medium-12 small-12 text-center">
            Partner Logo
        </div>
    </div>
</div>