<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>

<div class="row">
    <div class="column large medium small text-center">
        <h1>Header</h1>
    </div>
</div>
<div class="container">
    <div class="contain-to-grid">
        <div class="row">
            <div class="column callout panel large-3 medium-3 small-3">
                Logo
            </div>
            <div class="column callout panel large-1 medium-1 small-1">
                Lang
            </div>
            <div class="column callout panel large-8 medium-8 small-8">
                Navigation
            </div>
        </div>
    </div>
    <div class="row">
        <div class="column callout panel large-12 medium-12 small-12">
            Slider
        </div>
    </div>
    <div class="row">
        <div class="column callout panel small-10 small-centered">
            Booking
        </div>
    </div>
</div>