<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>

<div class="row">
    <div class="column large small medium text-center">
        <h1>Template 1</h1>
    </div>
</div>

<div class="row">
    <a target="_blank" href="<?=$this->url('phoenixTemplates-template1', array('action' => 'header'))?>" class="large medium small"><div class="column panel radius large-3 medium-3 small-1 text-center" data-equalizer><p>Header</p></div></a>
    <a target="_blank" href="<?=$this->url('phoenixTemplates-template1', array('action' => 'footer'))?>" class="large medium small"><div class="column panel radius large-3 medium-3 small-1 text-center" data-equalizer><p>Footer</p></div></a>
</div>

<div class="row">
    <a target="_blank" href="<?=$this->url('phoenixTemplates-template1', array('action' => 'home'))?>" class="large medium small"><div class="column panel radius large-3 medium-3 small-1 text-center" data-equalizer><p>Home</p></div></a>
    <a target="_blank" href="<?=$this->url('phoenixTemplates-template1', array('action' => 'room'))?>" class="large medium small"><div class="column panel radius large-3 medium-3 small-1 text-center" data-equalizer><p>Room</p></div></a>
    <a target="_blank" href="<?=$this->url('phoenixTemplates-template1', array('action' => '#'))?>" class="large medium small"><div class="column panel radius large-3 medium-3 small-1 text-center" data-equalizer><p>Special Offers</p></div></a>
    <a target="_blank" href="<?=$this->url('phoenixTemplates-template1', array('action' => '#'))?>" class="large medium small"><div class="column panel radius large-3 medium-3 small-1 text-center" data-equalizer><p>Gallery</p></div></a>
    <a target="_blank" href="<?=$this->url('phoenixTemplates-template1', array('action' => '#'))?>" class="large medium small"><div class="column panel radius large-3 medium-3 small-1 text-center" data-equalizer><p>Attractions</p></div></a>
    <a target="_blank" href="<?=$this->url('phoenixTemplates-template1', array('action' => '#'))?>" class="large medium small"><div class="column panel radius large-3 medium-3 small-1 text-center" data-equalizer><p>Events</p></div></a>
    <a target="_blank" href="<?=$this->url('phoenixTemplates-template1', array('action' => '#'))?>" class="large medium small"><div class="column panel radius large-3 medium-3 small-1 text-center" data-equalizer><p>Meeting Rooms</p></div></a>
    <a target="_blank" href="<?=$this->url('phoenixTemplates-template1', array('action' => '#'))?>" class="large medium small"><div class="column panel radius large-3 medium-3 small-1 text-center" data-equalizer><p>Dining</p></div></a>
    <a target="_blank" href="<?=$this->url('phoenixTemplates-template1', array('action' => '#'))?>" class="large medium small"><div class="column panel radius large-3 medium-3 small-1 text-center" data-equalizer><p>Facilities</p></div></a>
    <a target="_blank" href="<?=$this->url('phoenixTemplates-template1', array('action' => '#'))?>" class="large medium small"><div class="column panel radius large-3 medium-3 small-1 text-center" data-equalizer><p>Contact</p></div></a>
    <a target="_blank" href="<?=$this->url('phoenixTemplates-template1', array('action' => '#'))?>" class="large medium small"><div class="column panel radius large-3 medium-3 small-1 text-center" data-equalizer><p>Career</p></div></a>
    <a target="_blank" href="<?=$this->url('phoenixTemplates-template1', array('action' => '#'))?>" class="large medium small"><div class="column panel radius large-3 medium-3 small-1 text-center" data-equalizer><p>News</p></div></a>
    <a target="_blank" href="<?=$this->url('phoenixTemplates-template1', array('action' => '#'))?>" class="large medium small"><div class="column panel radius large-3 medium-3 small-1 text-center" data-equalizer><p>Press</p></div></a>
    <a target="_blank" href="<?=$this->url('phoenixTemplates-template1', array('action' => '#'))?>" class="large medium small"><div class="column panel radius large-3 medium-3 small-1 text-center" data-equalizer><p>Awards</p></div></a>
    <a target="_blank" href="<?=$this->url('phoenixTemplates-template1', array('action' => '#'))?>" class="large medium small"><div class="column panel radius large-3 medium-3 small-1 text-center" data-equalizer><p>Guest Reviews</p></div></a>
    <a target="_blank" href="<?=$this->url('phoenixTemplates-template1', array('action' => '#'))?>" class="large medium small"><div class="column panel radius large-3 medium-3 small-1 text-center" data-equalizer><p>About</p></div></a>
    <a target="_blank" href="<?=$this->url('phoenixTemplates-template1', array('action' => '#'))?>" class="large medium small"><div class="column panel radius large-3 medium-3 small-1 text-center" data-equalizer><p>Sitemap</p></div></a>
</div>