<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<div class="row">
    <div class="column large medium small text-center">
        <h1>Press</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="column large-12 medium-12 small-12 text-left">
            <p>Breadcrumb</p>
        </div>
    </div>
    <div class="row">
        <div contenteditable="false"  class="editable column large-12 medium-12 small-12 text-left">
            <h1>H1 for SEO purposes</h1>
        </div>
    </div>
    <div class="row">
        <div class="column callout panel large-12 medium-12 small-12 text-center">
            Press Widget
        </div>
    </div>
</div>