<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>

<div class="row">
    <div class="column large medium small text-center">
        <h1>Privacy Policy</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="column large-12 medium-12 small-12 text-left">
            <p>Breadcrumb</p>
        </div>
    </div>
    <div class="row">
        <div class="column large-12 medium-12 small-12 text-left">
            <h1>H1 for SEO purposes</h1>
        </div>
    </div>
    <div class="row">
        <div contenteditable="false"  class="editable column large-12 medium-12 small-12 text-left">
            <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.</p>
        </div>
    </div>
</div>