<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>

<div class="row">
    <div class="column large medium small text-center">
        <h1>Weddings</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="column large-12 medium-12 small-12 text-left">
            <p>Breadcrumb</p>
        </div>
    </div>
    <div class="row">
        <div contenteditable="false"  class="editable column large-12 medium-12 small-12 text-left">
            <h1>H1 for SEO purposes</h1>
            <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas.</p>
        </div>
    </div>
    <div class="row">
        <div class="column large-12 medium-12 small-12 text-left">
            <dl class="tabs" data-tab>
                <dd class="active"><a href="#panel1">Weddings</a></dd>
                <dd><a href="#panel2">Request Proposal</a></dd>
            </dl>
            <div class="tabs-content">
                <div class="content active text-left" id="panel1">
                    <div class="column callout panel large medium small text-center">
                        Wedding  Widget
                    </div>
                </div>
                <div class="content text-left" id="panel2">
                    <div class="column callout panel large medium small text-center">
                        Contact Form
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>