<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<div class="row">
    <div class="column large medium small text-center">
        <h1>What's on</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="column large-12 medium-12 small-12 text-left">
            <p>Breadcrumb</p>
        </div>
    </div>
    <div class="row">
        <div contenteditable="false"  class="editable column large-12 medium-12 small-12 text-left">
            <h1>H1 for SEO purposes</h1>
            <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod.</p>
        </div>
    </div>
    <div class="row">
        <div class="column callout panel large-12 medium-12 small-12 text-center">
            What's on Widget
        </div>
    </div>
</div>