<div id="editBox">
    <div id="editItemLangSelect" class="editItemLangSelect">
            <span>LANGUAGE &nbsp;</span>
            <?php echo $this->formElement($this->languageOptions);?>
        </div>
        <?= $this->partial('list-module/helpers/edit-item-actions') ?>
    <div class="editItemContent">
        <br/>

        <?php $form = $this->form; ?>
        <?php $form->setAttribute('action', $this->url('calendar-toolbox', array('action' => 'addEvent'))); ?>
        <?php $form->prepare(); ?>

        <div class="editItemMessage">
            <?php if ($this->userAdded) : ?>
                echo 'The Event Category has been added.<hr>';
            <?php endif; ?>

            <?php if ($this->hasErrors) : ?>
                <?= $this->formElementErrors($this->form); ?>
            <?php endif; ?>
        </div>

        <?php
            echo $this->form()->openTag($form);
            foreach ($this->form as $valForm) {
                if ($valForm instanceof \Zend\Form\Element\Hidden) {
                    echo $this->formHidden($valForm);
                } else {
                    echo '<p>' . $this->formLabel($valForm) . $this->formElement($valForm) . '</p>';
                    echo str_replace('Value is required', $valForm->getName() . ' is required', $this->formElementErrors($valForm, array('class' => 'error-inline')));
                }
            }
            echo $this->form()->closeTag();
        ?>
    </div>
    <?= $this->partial('list-module/helpers/edit-item-actions') ?>
</div>