<div id="editBox">
    <div id="editBoxHeader">
        <div id="editItemHeaderTitle"><?= $title ?></div>
         <?= $this->partial('list-module/helpers/edit-list-actions') ?>
    </div>
    <div class="editListContent">
        <form method="POST">
            <input type="hidden" name="action" value="" />
            <table class="table table-compacted" id="example">

			<thead>
                    <tr>
                        <th width="20px"></th>
                        <th width="40px">Name</th>
						<th width="40px">Url</th>
						<th width="40px">HighLights</th>                        
                        <th width="40px">Status</th>
                    </tr>
            </thead>
                <tbody id="sortable">
				<?php //var_dump($this->items); 
				//echo "edit-list executed"; ?>
                <?php foreach($this->items as $index => $eventList): ?>
                    <tr class="ui-state-default" data-itemId="<?= $eventList->getId() ?>">
                        <td><input type="checkbox" name="items[]" value="<?= $eventList->getId() ?>" /></td>
                        <td>
                            <a href="<?= $this->url('calendar-toolbox', array('subsite'=> $subsiteRoute, 'action'=>'editEvent', 'itemId'=>$eventList->getId())) ?>">
                                <?= $eventList->getTitle() ?>
                            </a>
                        </td>
                       <td><?= $eventList->getUrl() ?></td>
					   <td><?= $eventList->getHighlights() ?></td>
                        <td><?= $this->displayStatus($eventList->getStatus()) ?></td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </form>
        <?= $this->partial('list-module/helpers/edit-list-pagination') ?>
    </div>
</div>