<h2 id="currentModuleNameText">YouFirst
  <span id="currentModuleTextLeft"></span>
  <span id="currentModuleTextRight"></span>
</h2>
<div id="taskMenu">
  <ul id="taskMenu">
   <li>
      <a href="<?php echo $this->url ('youfirst-groups-legacy-toolbox', array('action' => 'viewList', 'langCode' => 'en'));?>">
	  View Dashboard
	  </a>
	</li>
	
	<li>
	 <a href="<?php echo $this->url ('youfirst-groups-legacy-toolbox', array('action' => 'viewList', 'langCode' => 'en'));?>">
	 View Accounts
	 </a>
	</li>

	<li>
	  <a href="<?php echo $this->url ('youfirst-groups-legacy-toolbox', array('action' => 'viewList', 'langCode' => 'en'));?>">
	  View Accounts
	  </a>
	 </li>
	
	
 </ul>
</div>