<div>
<?//= $this->partial('list-module/helpers/edit-list-actions') ?>
<?php //echo $this->inlineScript()->appendScript($this->listUpdateStatusScript());?>
    <?//= $this->headLink()->appendStylesheet($this->toolboxIncludeUrl . 'module/ListModule/view/layout/css/general.css'); ?>
    <?//= $this->headScript()->appendFile($this->toolboxIncludeUrl . 'module/ListModule/view/layout/js/jquery.simplePagination.js'); ?>
    <?//= $this->headScript()->appendFile($this->toolboxIncludeUrl . 'module/ListModule/view/layout/js/list-module.js'); ?>
testing form output
<?php
echo $stat;



?>

<table width="100%">
<tr>
<td>a </td>
<td> <input type="text">

</td>
</tr>
</table>


</div>




