<div id="editBox">
    <div id="editBoxHeader">
        <div id="editItemHeaderTitle"><?= $title ?></div>
        <?= $this->partial('list-module/helpers/edit-list-actions') ?>
    </div>
    <div class="editListContent">
        <form method="POST">
            <input type="hidden" name="action" value="" />
            <table class="table table-compacted" id="example">
                <thead>
                    <tr>
                        <th width="20px"></th>
                        <th>Incoming Link</th>
                        <th>Redirecting Link</th>
                        <th>Redirect Type</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($this->items as $page) {
                        ?>
                        <tr>
                            <td><input type="checkbox" name="items[]" value="<?= $page->getId() ?>" /></td>
                            <td><a href="<?= $this->url('linkRedirects-toolbox', array('action' => 'editItem', 'itemId' => $page->getId())) ?>"><?= $page->getIncomingUrl() ?></a></td>
                            <td><?= $page->getRedirectUrl() ?></td>
                            <td><?= $page->getResponse() ?></td>
                            <td class="statusText"><?= $this->displayStatus($page->getEntity()->getStatus()) ?></td>
                        </tr>
<?php } ?>
                </tbody>
            </table>
        </form>
    </div>
    <? //$this->partial('list-module/helpers/edit-list-pagination') ?>
</div>