<div id="editBox">
    <div id="editBoxHeader">
        <div id="editItemHeaderTitle"><?= $title ?></div>
        <?= $this->partial('list-module/helpers/edit-list-actions') ?>
    </div>
    <div class="editListContent">
        <form method="POST">
            <input type="hidden" name="action" value="" />
            <table class="table table-compacted" id="example">
                <thead>
                    <tr>
                        <th width="20px"></th>
                        <th>Link</th>
                        <th>Created Date</th>
                        <th>Status</th>

                    </tr>
                </thead>
                <tbody>
                    <?php
                    //var_dump($this->items);
                    foreach ($this->items as $page) {
                        $createdDateObject = $page->getCreated();
                        $createdDateArray = get_object_vars($createdDateObject);
                        ?>
                        <tr>
                            <td><input type="checkbox" name="items[]" value="<?= $page->getId() ?>" /></td>
                            <td><a href="<?= $this->url('linkRedirects-toolbox', array('action' => 'editItem', 'itemId' => $page->getId())) ?>"><?= $page->getUrl() ?></a></td>
                            <td><?= substr($createdDateArray['date'], 0, -9); ?></td>
                            <td><?= $page->getStatus() ?></td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </form>
    </div>
    <? //$this->partial('list-module/helpers/edit-list-pagination') ?>
</div>