
<div id="editBox">
    <div id="editBoxHeader">
        <div id="editItemHeaderTitle"><?= $title ?></div>
        <?= $this->partial('list-module/helpers/edit-list-actions') ?>
    </div>
    <div class="editListContent">
        <form method="POST">
            <input type="hidden" name="action" value="" />
            <table class="table table-compacted" id="example">
                <thead>
                    <tr>
                        <th width="20px"></th>
                        <th width="90px">Navigation Name</th>
                        <th width="90px">Navigation Key</th>
                        <th width="90px">Navigation Url</th>
                        <th width="90px">Order</th>
                        <th width="80px">Status</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($this->items as $index => $navigation): ?>
                    <tr>
                        <td><input type="checkbox" name="items[]" value="<?= $navigation->getId() ?>" /></td>
                        <td>
                            <a href="<?= $this->url('navigations-toolbox', array('subsite' => $subsiteRoute, 'action'=>'editItem', 'itemId'=>$navigation->getId())) ?>">
                                <?= $navigation->getNavigationName() ?>
                            </a>
                        </td>
                        <td><?= $navigation->getNavigationKey() ?></td>
                        <td><?= $navigation->getNavigationUrl() ?></td>
                        <td><?= $navigation->getNavigationOrder() ?></td>
                        <td><?= $this->displayStatus($navigation->getStatus()) ?></td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </form>
    </div>
    <?= $this->partial('list-module/helpers/edit-list-pagination') ?>
</div>