
<!-- CSS goes in the document HEAD or added to your external stylesheet -->
<style type="text/css">
    table.gridtable {
        font-family: verdana,arial,sans-serif;
        font-size:11px;
        color:#333333;
        border-width: 1px;
        border-color: #666666;
        border-collapse: collapse;
    }
    table.gridtable th {
        border-width: 1px;
        padding: 8px;
        border-style: solid;
        border-color: #666666;
        background-color: #dedede;
        text-transform: capitalize;
    }
    table.gridtable td {
        border-width: 1px;
        padding: 8px;
        border-style: solid;
        border-color: #666666;
        background-color: #ffffff;
    }
</style>
<!-- Table goes in the document BODY -->
<table class="gridtable">
    <tr>
        <th colspan="4"><?= $postDetails['formName']; ?> Request</th>
    </tr>

    <?php
    for ($i = 0; $i < (count($nameFields)); $i++) {
        echo '<tr><td>' . $nameFields[$i]['displayName'] . '</td><td>' . $postDetails[$nameFields[$i]['name']] . '</td></tr>';
    }
    ?>

</table>