<div id="editBox">
    <div id="editBoxHeader">
        <div id="editItemHeaderTitle"><?= $title ?></div>
         <?= $this->partial('list-module/helpers/edit-list-actions') ?>
    </div>
    <div class="editListContent">
        <form method="POST">
            <input type="hidden" name="action" value="" />
            <table class="table table-compacted" id="example">

			<thead>
                    <tr>
                        <th width="20px"></th>
                        <th width="40px">Title</th>
                        <th width="20px">Name</th>
						 <th width="90px">Comments</th>
                        <th width="40px">Status</th>
                    </tr>
                </thead>
                <tbody id="sortable">
                <?php foreach($this->items as $index => $phoenixReviews): ?>
                    <tr class="ui-state-default" data-itemId="<?= $phoenixReviews->getId() ?>">
                        <td><input type="checkbox" name="items[]" value="<?= $phoenixReviews->getId() ?>" /></td>
                        <td>
                            <a href="<?= $this->url('phoenixReview-toolbox', array('subsite'=> $subsiteRoute, 'action'=>'editItem', 'itemId'=>$phoenixReviews->getId())) ?>">
                                <?= $phoenixReviews->getTitle() ?>
                            </a>
                        </td>
                        <td><?= $phoenixReviews->getName() ?></td>
                        <td><?= $phoenixReviews->getContent() ?></td>
                        <td><?= $this->displayStatus($phoenixReviews->getStatus()) ?></td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </form>
        <?= $this->partial('list-module/helpers/edit-list-pagination') ?>
    </div>
</div>