<div id="editBox">
    <div id="editBoxHeader">
        <div id="editItemHeaderTitle">Edit Categories for <?= $moduleTitle ?></div>
        <?= $this->partial('list-module/helpers/edit-list-actions') ?>
    </div>
    <div class="editListContent">
        <form method="POST">
            <input type="hidden" name="action" value="" />
            <table class="table table-compacted" id="example">
                <thead>
                    <tr>
                        <th width="20px"></th>
                        <th>Name</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($this->items as $item) { ?>
                        <tr>
                            <td><input type="checkbox" name="items[]" value="<?= $item->getId() ?>" /></td>
                            <td><a href="<?= $this->url('categories-toolbox', array('action' => 'editItem', 'moduleId' => $moduleId, 'itemId' => $item->getId())) ?>"><?= $item->getName() ?></a></td>
                        </tr>
<?php } ?>
                </tbody>
            </table>
        </form>
    </div>
    <? //$this->partial('list-module/helpers/edit-list-pagination') ?>
</div>
<br />
<a href="<?= $this->url($returnRoute)?>">Back to <?=$returnName?></a>