
<div id="editBox">
    <div id="editBoxHeader">
        <div id="editItemHeaderTitle"><?= $title ?></div>
        <?= $this->partial('list-module/helpers/edit-list-actions') ?>
    </div>
    <div class="editListContent">
        <form method="POST">
            <input type="hidden" name="action" value="" />
            <table class="table table-compacted" id="example">
                <thead>
                    <tr>
                        <th width="20px"></th>
                        <th width="90px">Footer Name</th>
                        <th width="90px">Footer Key</th>
                        <th width="90px">Footer Url</th>
                        <th width="90px">Order</th>
                        <th width="80px">Status</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($this->items as $index => $seoMetaText): ?>
                    <tr>
                        <td><input type="checkbox" name="items[]" value="<?= $seoMetaText->getId() ?>" /></td>
                        <td>
                            <a href="<?= $this->url('footer-toolbox', array('subsite' => $subsiteRoute, 'action'=>'editItem', 'itemId'=>$seoMetaText->getId())) ?>">
                                <?= $seoMetaText->getFooterName() ?>
                            </a>
                        </td>
                        <td><?= $seoMetaText->getFooterKey() ?></td>
                        <td><?= $seoMetaText->getFooterUrl() ?></td>
                        <td><?= $seoMetaText->getFooterOrder() ?></td>
                        <td><?= $this->displayStatus($seoMetaText->getStatus()) ?></td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </form>
    </div>
    <?= $this->partial('list-module/helpers/edit-list-pagination') ?>
</div>